Develop (#1)
* Check if the post/comment exists

Just realized that if the user left the caption empty and after the
post date write an comment, it doesn't count as a caption. Fixed that
by getting the first comment from the post.

Also added a check if “PostPage” variable exists in “check_link”.

* Update README.md

* Update README.md

* Delete chromedriver

* fixed problem with no follower count on completely new account

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Update README.md

* Fix like when the "Get the App" bar is visible

Instead of calling Selenium method Click, get the Class of the Like
Button and do a Click() with Javascript.

If there’s an element above the Like Button, Selenium doesn’t hit it
and throw an error, JS don’t.

* changed to use execute script

* Update README.md

* Added Windows Install Script

* Create How_To_DO_Centos.md

* Update How_To_DO_Centos.md

* Fix How_To_DO_Centos formatting

* Added Mac Install Script

* Update How_To_DO_Centos.md

* Introduced option to ignore pictures from certain users
Usage:
    .set_ignore_users([usernames])

Also changed the behaviour when checking for ignores based on keywords, now it includes all the comments made by the owner (sometimes the owner place tags in their first comment, not necessarily the first comment of the picture)

Finally, added some verbosity to track why an image has been flagged as inappropriate (which tag was responsible or the user name if it’s blacklisted).

* Update like_util.py

* docs

* attempt to fix chrome crash bug
also changed print to keep the style consistency!

* treat ‘use_new_styles’

* Set theme jekyll-theme-cayman

* Addition of directory for pages

* Changed Index from Readme to new text

* Set theme jekyll-theme-cayman

* Lets try MD

* Minor Fomatting

* sanity checks

* Write() once

* Update README.md

* Update README.md

* Update index.md

* Set theme jekyll-theme-cayman

* Delete _config.yml

* Implement #55

Also improved how we find links so we can get the proper amount of links for the appropriate media type.

* Minor fix (forgot about one return!)

* Update instapy.py

* Added How To Do on Ubuntu and moved the How To Do on Centos to /docs

* ensure we can actually get the new posts

* Description encoding problem solved.

* Update index.md

* Update index.md

* Update index.md

* Update like_util.py

* added Dockerfile

* changed repo to use the one without desc printing

* ✨ Add cleanup of apt-get packages

* 🔥 Remove unused env variables

* ✨ Add env variables for download urls

* ✨ Add python get.env

* 📝 Update readme with docker instructions

* 🔥 Remove apt lists

* update How_to_do_Centos

Added line no. 44 ( Directory was incorrect for pip install)

* Added Linux Mint Install Script

* Fixed linux32.sh executing permission

* Fixed wrong installation source for python-dev

* 🐛 Fix locale

* Simplify boolean logic

* use any with generators to speed up/clean up code

* Update README.md

* Update README.md

* Update index.md

* Addition of checking follower count

Adding functionality that checks the numbers of followers a user has
and compares this to a user set value and if this exceeds the value no
further interaction happens.

Command:
.set_upper_follower_count(limit = 250) \

Addition of this to documentation and readme also

* From large Number to 0

Change of upper bound from 10000000000 to 0 as per suggestions

* New Following Feature - follow by a list

* Change requestes implemented

* Rebased and added lower follower limit

Rebased the branch.

Added functionality that factors in a limit of a minimum number of
followers a user should have before further interaction.

As such added to Readme and Docs

* Merge branch 'master' of https://github.com/timgrossmann/InstaPy into filter_media

Improved tag detection to be case-insensitive!

* Update instapy.py

rollback the `implicitly_wait` to its original value.

* requested changes

* Introduced random times to the script.

Times that were fixed before now falls in a range +/- 50% from the original value selected from a normal distribution.
e.g. `sleep(2)` can now be anywhere in-between `sleep(1) and `sleep(3)`, normally distributed in this range, centered around `2`.

* Image Update

* Update time_util.py

* No title is set in the official page of InstaPy #99

* Title Tag Test

* Conflict resolution

* Update README.md

* Update README.md

* Update index.md

* Update index.md

* typo

* add switch to check if all clarifAI tags are present or only one

* Update index.md

* Update index.md

* fix import typos

* Change request fixed - print statement

* expand the tuple instead of accessing them by position

* Fix docker build command

* Syntax error: Missing parentheses in call to 'print' in like_util.py, line 80
Coherency: Change double quotes to single quotes in like_util.py, line 80

* import typo

* Fixed mac.sh script

OOB OSx doesn’t have wget and there’s no necessity of installing pip on
OSx.
So I’ve changed the WGET for CURL and removed the “pip install .”, go
to the “python setup.py install” way.

Also, fixes part of #112

* Fix ‘Page not Found’ issue.

* Solves ‘Invalid Like Element’

* Update like_util.py

* Only get number of followers if actually needs to.

Avoid going to the user profile page and back if we are not filtering by number of followers.

* Update README.md

Replaced html tags with markdown equivalents

* Update README.md

* Update like_util.py

* Update quickstart.py

* Update Dockerfile

* improved like_from_image and like_by_tags doc

* Update index.md

* Update index.md

* Update index.md

* Changed print style to newer `.format` one.
Fixed issue where parenthesis were being printed together with the text.

* Fix #118

Instead of aborting if too few images, work with the ones we have (if any), than go to next tag.
Also improved the `while` loop to avoid trying to load more images than really available.

* Update README.md

* Update index.md

* Update README.md

* Update index.md

* idea del

* .format()

* fix to instagram graphql change

* work with and without graphql

* semantics: instapy/unfollow_util.py acc_to_follow --->> follow_given_user refactored

* Delete .DS_Store

* Fixed login_util

Changed the elements and make it work on every login scenario.

Also added the support to ActionChains to avoid Instagram anti-bot
protection and simulate mouse movements

* Update index.md

* Update index.md

* Update like_util.py

* Update like_util.py

fix #147 and #148

* Fix #152

* Update README.md

* Update index.md

* Removed window coming to front

* Fixed comment_util emoji output

Added unicode flag to string.format

* Fixed issue with commented display lines

* Update README.md

* Update index.md

* Update Dockerfile

* Update README.md

* Added Emoji section

* Update README.md

* Update README.md

* Refactor preview.
Include breaking changes to make it more logical and reduce confusion

Working:
* Basic like by tags
* ignore_users
* follower_limit
* dont_like
* like_anyway
* like_tags
* like_media

Need testing:
* Follow utilities
* Comment utilities

Not working:
* like_from_image
* follow_by_list
* follow_restrictions (only follow an specific amount of times)
* log_follower_num
* unfollow (make it so to only unfollow those followed by the script?)
* clarifai (make it v2?)

Need to do:
* Documentation and examples

* Add nogui instapy constructor parameter

* Update documentation about the nogui parameter

* Update README.md

* Update README.md

* Update index.md

* Update README.md

* Update README.md

* Fixed `print`

Changed flag `virtual` to `nogui` as it makes more sense.

* Fix do like

Fix issue when perform like on an already liked.

* Fixed is_video not defined issue

* Fixed an encoding issue when writing log

When client encoding not support some unicode characters, raises the error.
sample error:
UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f6b2' in position
251: illegal multibyte sequence

* Fix invalid comment input element